### ISSUE TITLE
sayitni main qismini "header-paragraph"ni to'g'irlash kerak

### ISSUE THREAD

**Issue by frontendoniyorbek** [MIRZOULUGBEK9008/apple-watch-selfmade#4]
https://prnt.sc/LyZL6BPSTQWJ
margin berishda hato margin-top: 0 bo'lishi kerak
linkni ustiga chqib ketgan
linkni display:inline-blok; qilib qo'ying

**Comment by MIRZOULUGBEK9008** [comment]
#fix
