### ISSUE TITLE
sayitni class=hero-one-list ; ni css  qismini to'g'irlash kerak

### ISSUE THREAD

**Issue by frontendoniyorbek** [MIRZOULUGBEK9008/apple-watch-selfmade#5]
bu yerda **p** elementga margin bergansiz shuni margin-top:0 teng qilib qo'yish kerak headingda ham margin bor bunda ham bir birinikini ustiga chiqib ketyabdi
https://prnt.sc/QvvnZ-SgWR7j

**Comment by MIRZOULUGBEK9008** [comment]
#fix
