### ISSUE TITLE
sayitni  class:learn-more-list; qismida hatolik bor

### ISSUE THREAD

**Issue by frontendoniyorbek** [MIRZOULUGBEK9008/apple-watch-selfmade#6]
https://github.com/MIRZOULUGBEK9008/apple-watch-selfmade/blob/0b72aab062448d11be3607e1e4cd2ff6e035e949/index.html#L87
https://prnt.sc/_H2sfnkTPE7x
**hr** ni margin:0; qilib kiyin **li** ga     margin-right: 10px; berish kerak

**Comment by MIRZOULUGBEK9008** [comment]
#fix
